#ifndef FUNC_H_
#define FUNC_H_

int pow(int, int);
int waveIn(TCHAR *, LPHWAVEOUT, LPWAVEFORMATEX, LPWAVEHDR);
LPDWORD bmptoDIB(TCHAR *, LPBITMAPINFO);
BOOL CALLBACK DlgProc(HWND, UINT, WPARAM, LPARAM);
BOOL CALLBACK DlgProc2(HWND, UINT, WPARAM, LPARAM);

#endif
